name: 'Deploy to fargate cluster'
description: 'Assuming a IAM role and deploying to a Fargate cluster'
inputs:
  role-to-assume:
    description: 'IAM role to assume before deploying'
    required: true
  service:
    description: 'Name of the service'
    required: true
  service:
    description: 'Full name of the docker image'
    required: true
  container-image:
    description: 'Full name of the docker image'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.role-to-assume }}
    - ${{ inputs.cluster }}
    - ${{ inputs.service }}
    - ${{ inputs.container-image }}
